---
- hosts: all
  become: true
  tasks:
    - name: install puppet repo rpm
      yum:
        name: https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
        state: present

    - name: Update all packages
      yum: name=* state=present update_cache=yes

    - name: Install packages
      yum: state=present name={{ item }}
      with_items:
        - puppet-agent
        - ntp

