---
- hosts: all
  become: true
  tasks:
    - name: install puppet repo rpm
      yum:
        name: https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
        state: present

    - name: Update all packages
      yum: name=* state=present update_cache=yes

    - name: Install packages
      yum: state=present name={{ item }}
      with_items:
        - puppet-agent

- hosts: bootstrap
  become: true
  tasks:
    - name: execute puppet for bootstrap
      command: /opt/puppetlabs/bin/puppet apply site.pp
      args:
        chdir: /vagrant

- hosts: master
  become: true
  tasks:
    - name: execute puppet for master
      command: /opt/puppetlabs/bin/puppet apply site.pp
      args:
        chdir: /vagrant

- hosts: private-agent
  become: true
  tasks:
    - name: execute puppet for private-agent
      command: /opt/puppetlabs/bin/puppet apply site.pp
      args:
        chdir: /vagrant      


